[package]
name = "web-vlog"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
sha1 = { version = "0.10", default-features = false }
v-log = { path = "../v-log" } #"0.1"
log = "0.4"

[dev-dependencies]
open = "5"
